// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 the Schmaloogium contributors

package com.schmaloogium.engine.buffers;

/** Closed texture-binding rejection vocabulary (Phase 5 Doc §2.4). */
public enum TextureBindingRejection {
    INVALID_INPUT, WRONG_THREAD, STALE_ESTATE_GENERATION, STALE_DEPTH_ATTACHMENT_EPOCH,
    NO_OPEN_FRAME, WRONG_FRAME_ID, INVALID_PASS_SNAPSHOT, INVALID_PROGRAM_SELECTION,
    PROGRAM_SELECTION_MISMATCH, STALE_REGISTRY_GENERATION, SAMPLER_LAYOUT_MISMATCH,
    CLOSED_OVERLAY_LEASE, OVERLAY_PUBLICATION_ID_MISMATCH, REGISTRY_FINGERPRINT_MISMATCH,
    CONFIGURATION_FINGERPRINT_MISMATCH
}
