// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 the Schmaloogium contributors

package com.schmaloogium.engine.expr.api;

import java.util.List;

/** Authored, independently derived expectations for one conformance case (§5.6); never
 * generated by the evaluator under test. Diagnostic kind/ID/location lists have identical
 * lengths and matching order. */
public record ExpressionConformanceExpected(
        ExpressionConformanceBuild build,
        List<ExpressionDiagnosticKind> loadDiagnosticKinds,
        List<String> loadStableDiagnosticIds,
        List<ExpressionDiagnosticLocation> loadDiagnosticLocations,
        List<ExpressionConformanceObservation> refreshes) {

    public ExpressionConformanceExpected {
        loadDiagnosticKinds = List.copyOf(loadDiagnosticKinds);
        loadStableDiagnosticIds = List.copyOf(loadStableDiagnosticIds);
        loadDiagnosticLocations = List.copyOf(loadDiagnosticLocations);
        refreshes = List.copyOf(refreshes);
    }
}
